name       : python-mpmath
version    : 1.2.1
release    : 4
source     :
    - https://files.pythonhosted.org/packages/source/m/mpmath/mpmath-1.2.1.tar.gz : 79ffb45cf9f4b101a807595bcb3e72e0396202e0b1d25d689134b48c4216a81a
homepage   : https://mpmath.org/
license    : BSD-3-Clause
component  : programming.python
summary    : Python library for arbitrary-precision floating-point arithmetic
description: |
    Mpmath is a pure-Python library for multiprecision floating-point arithmetic. It provides a set of transcendental functions, unlimited exponent sizes, complex numbers, interval arithmetic, numerical integration and differentiation, root-finding, linear algebra, and others. Almost any calculation can be performed just as well at 10-digit or 1000-digit precision, and in many cases, mpmath implements algorithms that scale well for high precision work. If available, mpmath will (optionally) use gmpy to speed up high precision operations.
replaces   :
    - python3-mpmath
builddeps  :
    - python-pytest
    - python-setuptools-scm
rundeps    :
    - matplotlib
    - python-gmpy2
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test py.test3 -v --pyargs mpmath
