name       : python-mpmath
version    : 1.1.0
release    : 2
source     :
    - https://github.com/fredrik-johansson/mpmath/archive/1.1.0.tar.gz : 16c01d589bcb1be5cab3a07de2855b578e5fc4a7882fb61a15f2aaf118fdd06e
homepage   : http://mpmath.org/
license    : BSD-3-Clause
component  : programming.python
summary    : Python library for arbitrary-precision floating-point arithmetic
description: |
    Mpmath is a pure-Python library for multiprecision floating-point arithmetic. It provides a set of transcendental functions, unlimited exponent sizes, complex numbers, interval arithmetic, numerical integration and differentiation, root-finding, linear algebra, and others. Almost any calculation can be performed just as well at 10-digit or 1000-digit precision, and in many cases, mpmath implements algorithms that scale well for high precision work. If available, mpmath will (optionally) use gmpy to speed up high precision operations.
replaces   :
    - python3-mpmath
builddeps  :
    - python-pytest
rundeps    :
    - matplotlib
    - python-gmpy2
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test py.test3 -v --pyargs mpmath
